runtime: nodejs10

manual_scaling:
  instances: 1

handlers:
  - url: /(.*\.(css|eot|gz|html|ico|js|map|png|jpg|svg|ttf|woff|woff2))
    static_files: dist/Sponsorloop/\1
    upload: dist/Sponsorloop/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  - url: /.*
    static_files: dist/Sponsorloop/index.html
    upload: dist/Sponsorloop/index.html
