# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to google cloud

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build-prod
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: kkl-sponsorloop
          APPLICATION_CREDENTIALS: ${{secrets.AZURE_ACCOUNT}}
        with:
          args: app deploy app.yaml
